# .env
spring.config.import=optional:file:.env.backend[.properties]

spring.application.name=backend
spring.main.banner-mode=off

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDLAUTO:validate}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:4h}

cors.allowed.origin=${CORS_ALLOWED_ORIGIN}

s3.endpoint=${S3_ENDPOINT}
s3.region=${S3_REGION}
s3.accesskey=${S3_ACCESSKEY}
s3.secretkey=${S3_SECRETKEY}
s3.buckets.img=${S3_BUCKETS_IMG}