spring.application.name=backend
spring.main.banner-mode=off

spring.config.import=classpath:env.properties,classpath:secret.properties

spring.datasource.url=${db.jdbc-url}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${db.hibernate.mode}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${auth.tokens.secret-key}
jwt.expiration=${auth.tokens.expiration}